eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  liquibase:
    enabled: on
    url: jdbc:postgresql://localhost:5433/delivery_club
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.xml