spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${POSTGRES:localhost}:5433/delivery_club
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
    change-log: "db/changelog/db.changelog-master.xml"

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  signing:
    key: t6w9z$B&E)H@McQfTjWnZr4u7x!A%D*F

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG