spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${POSTGRES:localhost}:5433/delivery_club
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
    change-log: "db/changelog/db.changelog-master.xml"

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    hostname: order-service
  client:
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
