spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:delivery_club}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        show_sql: false

eureka:
  instance:
    prefer-ip-address: true
    hostname: courier-service
  client:
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
